name: Build
on: [push]
env:
  PROJECT_NAME: kubectl-node-provider-id
jobs:
  # grab the current version from cargo.toml
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get project version
        id: version
        run: |
          project_version=$(cargo metadata --format-version 1 | jq -r ".packages[] | select(.name == \"${PROJECT_NAME}\") | .version")
          echo "project_version=$project_version" >> $GITHUB_OUTPUT
    outputs:
      project_version: ${{ steps.version.outputs.project_version }}

  # build cross-platform binaries
  build:
    runs-on: ${{ matrix.runner }}
    needs:
      - version
    env:
      PROJECT_VERSION: ${{ needs.version.outputs.project_version }}
    strategy:
      matrix:
        include:
          - name: linux-amd64
            runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - name: linux-arm64
            runner: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            cross: true
          - name: win-amd64
            runner: windows-latest
            target: x86_64-pc-windows-msvc
          - name: macos-amd64
            runner: macos-latest
            target: x86_64-apple-darwin
          - name: macos-arm64
            runner: macos-latest
            target: aarch64-apple-darwin

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Cache
        uses: Swatinem/rust-cache@v2

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: "${{ matrix.target }}"

      - name: cargo-binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Build Binary
        shell: bash
        run: |
          CARGO_BUILD_CMD=cargo
          if [ -n "${CROSS}" ]; then
            echo "Using Cross"
            cargo binstall cross --no-confirm
            CARGO_BUILD_CMD=cross
          fi
          ${CARGO_BUILD_CMD} build --verbose --locked --release --target ${{ matrix.target }}
        env:
          CROSS: "${{ matrix.cross }}"

      - name: Copy Binary
        shell: bash
        run: |
          BIN_SUFFIX=""
          if [[ "${{ matrix.runner }}" == "windows-latest" ]]; then
            BIN_SUFFIX=".exe"
          fi

          # built binary output location
          BIN_OUTPUT="target/${{ matrix.target }}/release/${PROJECT_NAME}${BIN_SUFFIX}"

          # friendly name for the binary
          BIN_RELEASE="${PROJECT_NAME}${BIN_SUFFIX}"

          # move to artifacts directory
          mkdir -p ./artifacts
          mv "${BIN_OUTPUT}" "./artifacts/${BIN_RELEASE}"

      - name: Compress binary
        if: runner.os != 'Windows'
        run: |
          cp LICENSE ./artifacts
          tar -czvf ./${PROJECT_NAME}_${PROJECT_VERSION}-${{ matrix.name }}.tar.gz -C ./artifacts .

      - name: Compress binary (windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Copy-Item -Path "LICENSE" -Destination ".\artifacts"
          Compress-Archive -Path .\artifacts\* -DestinationPath .\${env:PROJECT_NAME}_${env:PROJECT_VERSION}-${{ matrix.name }}.zip

      - name: Upload binary
        if: runner.os != 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PROJECT_NAME }}_${{ env.PROJECT_VERSION }}-${{ matrix.name }}.tar.gz
          path: ${{ env.PROJECT_NAME }}_${{ env.PROJECT_VERSION }}-${{ matrix.name }}.tar.gz
          if-no-files-found: error
          retention-days: 1

      - name: Upload binary (windows)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PROJECT_NAME }}_${{ env.PROJECT_VERSION }}-${{ matrix.name }}.zip
          path: ${{ env.PROJECT_NAME }}_${{ env.PROJECT_VERSION }}-${{ matrix.name }}.zip
          if-no-files-found: error
          retention-days: 1

  # release the binaries
  release:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/download-artifact@v4
        if: startsWith(github.ref, 'refs/tags/')

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: true
          generate_release_notes: true
          name: "${{ github.ref_name }}"
          fail_on_unmatched_files: true
          files: |
            ./**/*.tar.gz
            ./**/*.zip
